### ISSUE TITLE
Call function after each step

### ISSUE THREAD

**Issue by SourceCodeplz** [guins/jQuery.scrollSections#2]
Hey, first of all thank you very much for a great plugin!

I have some JS image sliders on every section and was wondering how would I go about loading the specific slider only on the active section.

From the documentation I see "before" and "after" can have functions. But how do I reference (make the connection) to my actual image slider on that specific active section. Can I use the "attr" for that?

Thank you again!

**Comment by guins** [comment]
Hi Daniel, thanks for your comment!

Of course you could use the "attr" of each section, but I did an improvement to my plugin in order to simplify the task.
Now before and after callbacks have two parameters to target either the current, next or previous sections.

Have a look at the ./example/callback.html file to find a complete example.

Cheers

**Comment by SourceCodeplz** [comment]
That's brilliant! The example is exactly what I needed. thank you very much
